Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FinalProject.Models
{
    public class Event
    {
        public class DateRangeAttribute : ValidationAttribute
        {

            public int FirstDateYears { get; set; }
            public int SecondDateYears { get; set; }

            public DateRangeAttribute()
            {
                FirstDateYears = 1;
                
            }

            public override bool IsValid(object value)
            {
                DateTime date = DateTime.Parse(value.ToString());
                if (date > DateTime.Now && date <= DateTime.Now.AddYears(FirstDateYears))
                {
                    return true;
                }
                return false;
            }

        }


        [Key]
        public int EventID { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Chef Name:")]
        public String EventChefName { get; set; }
        [Required]
        [StringLength(300)]
        [Display(Name = "About the Event:")]
        public String EventDetails { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        [DateRange(ErrorMessage = "Your event must be in the future, and must be within a year from today's date")]
        [Display(Name = "Date of Event:")]
        public DateTime EventDate { get; set; }
        [Required]
        [EmailAddress]
        [StringLength(50)]
        [Display(Name = "Event Hosts Email:")]
        public String EventEmailOfPoster { get; set; }
        [Required]
        [Range(1, 50)]
        [Display(Name = "How many invitees for Event:")]
        public int EventSize { get; set; }
        [Display(Name = "Is the Event full? :")]
        public bool EventFull { get; set; }

        public virtual UserType TypeID { get; set; }

    }
}

Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    [Authorize]
    public class EventsController : Controller
    {
        public Event events = new Event();

        

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Events
        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        // GET: Events/Details/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventID,EventChefName,EventDetails,EventDate,EventEmailOfPoster,EventSize,EventFull")] Event @event)
        {
            
                if (ModelState.IsValid)
                {                    
                        db.Events.Add(@event);
                        db.SaveChanges();                
                        
                    return RedirectToAction("Index");
                }
                        
            return View(@event);
        }

        // GET: Events/Edit/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")] 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventID,EventChefName,EventDetails,EventDate,EventEmailOfPoster,EventSize,EventFull")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        // GET: Events/Delete/5
        [Authorize(Roles = "Admin")] 
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Events/Delete/5
        [Authorize(Roles = "Admin")] 
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Events/Create.cshtml
@model FinalProject.Models.Event

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EventChefName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventChefName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventChefName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDetails, "", new { @class = "text-danger" })
            </div>
        </div>
         
        <div class="form-group">
            
                @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.EventEmailOfPoster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventEmailOfPoster, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventEmailOfPoster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventFull, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EventFull)
                    @Html.ValidationMessageFor(model => model.EventFull, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Events/Delete.cshtml
@model FinalProject.Models.Event

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventChefName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventChefName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventEmailOfPoster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventEmailOfPoster)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventFull)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventFull)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Events/Details.cshtml
@model FinalProject.Models.Event

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EventChefName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventChefName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDetails)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDetails)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventEmailOfPoster)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventEmailOfPoster)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventSize)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventSize)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventFull)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventFull)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Events/Edit.cshtml
@model FinalProject.Models.Event

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.EventID)

        <div class="form-group">
            @Html.LabelFor(model => model.EventChefName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventChefName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventChefName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDetails, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDetails, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDetails, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventEmailOfPoster, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventEmailOfPoster, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventEmailOfPoster, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventSize, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EventSize, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EventSize, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventFull, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EventFull)
                    @Html.ValidationMessageFor(model => model.EventFull, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Events/Index.cshtml
@model IEnumerable<FinalProject.Models.Event>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Events</h2>
<br />
<br />

<p>
    @Html.ActionLink("Create New", "Create", "Events", null, new { @class = "btn btn-primary" })
</p>
<table class="table table-bordered table-striped table-condensed">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EventChefName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDetails)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventEmailOfPoster)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventSize)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventFull)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EventChefName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventDetails)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventEmailOfPoster)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventSize)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventFull)
        </td>
        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
            {
             <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.EventID }) |
                @Html.ActionLink("Details", "Details", new { id=item.EventID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.EventID })
            </td>
            }
    </tr>
}

</table>