Models/ImageGallery.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace FinalProject.Models
{
    public class ImageGallery
    {
        public ImageGallery()
        {
            ImageList = new List<string>();
        }
        [Key]
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string ImagePath { get; set; }
        public List<string> ImageList { get; set; }
    }
}

Controllers/ImageGalleriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;

namespace FinalProject.Controllers
{
    [Authorize]
    public class ImageGalleriesController : Controller
    {
        private ImageDbContext db = new ImageDbContext();

        public ActionResult Index()
        {
            var imagesModel = new ImageGallery();
            var imageFiles = Directory.GetFiles(Server.MapPath("~/Gallery/"));
            foreach (var item in imageFiles)
            {
                imagesModel.ImageList.Add(Path.GetFileName(item));
            }
            return View(imagesModel);
        }
        [HttpGet]

        public ActionResult UploadImage()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UploadImageMethod()
        {
            if (Request.Files.Count != 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    int fileSize = file.ContentLength;
                    string fileName = file.FileName;
                    file.SaveAs(Server.MapPath("~/Gallery/" + fileName));
                    ImageGallery imageGallery = new ImageGallery();
                    imageGallery.ID = Guid.NewGuid();
                    imageGallery.Name = fileName;
                    imageGallery.ImagePath = "~/Gallery/" + fileName;
                    db.ImageGallery.Add(imageGallery);
                    db.SaveChanges();
                }
                return Content("Success");
            }
            return Content("failed");
        }
    }
}

Views/ImageGalleries/Create.cshtml
@model FinalProject.Models.ImageGallery

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ImageGallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ImageGalleries/Delete.cshtml
@model FinalProject.Models.ImageGallery

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ImageGallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/ImageGalleries/Details.cshtml
@model FinalProject.Models.ImageGallery

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>ImageGallery</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/ImageGalleries/Edit.cshtml
@model FinalProject.Models.ImageGallery

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ImageGallery</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/ImageGalleries/Index.cshtml
@model FinalProject.Models.ImageGallery

@{
    ViewBag.Title = "Image Gallery";
}

<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.mousewheel-3.0.6.pack.js"></script>
<script src="~/Scripts/jquery.fancybox.js?v=2.1.3"></script>
<link href="~/Content/jquery.fancybox.css?v=2.1.2" rel="stylesheet" media="screen" />
<link href="~/Scripts/jquery.fancybox.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {
        $("#ShowImage").fancybox({
            helpers:
            {
                title:
                {
                    type: 'float'
                }
            }
        });
    });
</script>
<style type="text/css">
    .imgBox {
        width: 200px;
        height: 200px;
        opacity: 1.0;
        filter: alpha(opacity=100);
    }

        .imgBox:hover {
            -moz-box-shadow: 0 0 10px #ccc;
            -webkit-box-shadow: 0 0 10px #ccc;
            box-shadow: 0 0 10px #ccc;
            opacity: 0.4;
            filter: alpha(opacity=40);
        }
</style>
<div class="jumbotron" style="height:600px;">
    
        <p>
            <a class="imageGallery btn btn-primary" data-fancybox-type="iframe"
               href="@Url.Action("UploadImage", "ImageGalleries")">Upload New Image</a>
        </p>
    
    <div style="border-bottom:1px solid Red;"></div>
    @if (Model.ImageList.Count > 0)
    {
        <div class="row-fluid">
            <div class="span2">
                <div class="item">
                    @foreach (var image in Model.ImageList)
                    {
                        <div style=" margin:10px; float:left; height:200px; overflow:hidden; width:200px;">
                            <a id="ShowImage" class="fancybox-button" data-rel="fancybox-button"
                               title="Photo" href="@Url.Content("~/Gallery/"+ image)">
                                <div class="zoom">
                                    <img src="@Url.Content("~/Gallery/" + image)" class="imgBox" />
                                    <div class="zoom-icon"></div>
                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('.imageGallery').fancybox({
            fitToView: false,
            width: '600px',
            height: '400px',
            autoSize: false,
            closeClick: false,
            openEffect: 'none',
            closeEffect: 'none',
            padding: 0,
            closeBtn: false,
            'afterClose': function () {
                window.location.reload();
            },
        });
    });
</script>

Views/ImageGalleries/UploadImage.cshtml
@{
    ViewBag.Title = "UploadImage";
}

<html>
<head>
    <title>Image Gallery</title>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script type="text/javascript">
        window.onload = function ()
        {
            document.getElementById('imageUploadId').onsubmit = function ()
            {
                var formdata = new FormData();
                var fileInput = document.getElementById('fileInputType');
                for (i = 0; i < fileInput.files.length; i++)
                {
                    formdata.append(fileInput.files[i].name, fileInput.files[i]);
                }
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '/ImageGalleries/UploadImageMethod');
                xhr.send(formdata);
                xhr.onreadystatechange = function ()
                {
                    if (xhr.readyState == 4 && xhr.status == 200)
                    {
                        if (xhr.responseText == "Success")
                        {
                            alert("Upload image successfully.");
                            parent.jQuery.fancybox.close();
                        }
                        else
                        {
                            alert("Error occurred.! Please try again");
                        }
                    }
                }
                return false;
            }
        }
    </script>

</head>
<body style="background-color:#fff">
    <div style="height:400px; border:1px solid;">
        <div style="width: 100%; height: 50px; border-bottom: 1px solid #808080; background-color: #66CCFF; ">
            <div style="float:right; height:30px; width:30px; margin-top:10px;
                border-left:0px solid #c8c8c8">
                <a href="javascript:parent.jQuery.fancybox.close();"
                   style="color: orange; cursor: pointer; text-decoration: none;">
                    <img src="../Content/fullscreenButton.png">
                </a>
            </div>
        </div>
        <div>
            <div style="margin-left:80px; float:left; width:500px;
                  height:270px; border: 0px solid black;">
                <div>
                    <br />
                    <form id="imageUploadId">
                        <h3>Upload a picture</h3>
                        <input id="fileInputType" type="file" multiple class="fileUpload"
                               style="width:300px;"><br />
                        <p style="color: #0066FF">
                            You Can Upload a JPG, GIF, Or PNG File.
                            This example of upload image from Ajax and Image Gallery
                        </p>
                        <input type="submit" class="btn btn-success" value="Image Upload" />
                    </form>
                </div>
            </div>
        </div>
        <div style="width:100%; margin-top:290px; border-bottom:1px solid #808080"></div>
        <div style="background-color: #66CCFF; height:57px; margin-top:-20px;">
            <div style="text-align:center; margin-top:20px;"><p>2014 &copy; Admin</p></div>
        </div>
    </div>
</body>
</html>